apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: {{ .Release.Name }}-worker
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-worker # has to match .spec.template.metadata.labels
  replicas: 1 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-worker # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: worker
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if eq .Values.mode "dev" }}
          args: ["npm", "run", "dev"]
          {{- else }}
          args: ["./app", "start", "worker"]
          {{- end }}
          ports:
            - containerPort: 8000
              name: worker
