apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
    name: {{ .Chart.Name }}-worker-scaler
spec:
    scaleTargetRef:
        kind: StatefulSet
        name: {{ .Chart.Name }}-worker
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Chart.Name }}-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-worker # has to match .spec.template.metadata.labels
  minReadySeconds: 10 # by default is 0
  template: 
    metadata:
      labels:
        app: {{ .Chart.Name }}-worker # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      initContainers:
      {{ include "initCheckContainers" . | nindent 6}}
      containers:
        - name: worker
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if eq .Values.mode "development" }}
          args: ["npm", "run", "dev:worker"]
          {{- else }}
          args: ["./app", "start", "worker"]
          {{- end }}
          ports:
            - containerPort: 8000
              name: worker
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-config
            - secretRef:
                name: {{ .Release.Name }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-redis
                  key: redis-password
                  optional: false
