kind: Config
apiVersion: 'skaffold/v2beta28'
build:
  artifacts:
    - image: super-app
      context: .
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: apps/**/*
            dest: .
          - src: packages/**/*
            dest: .
  tagPolicy:
    gitCommit:
      variant: TreeSha
  local:
    push: false
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: super-app
        chartPath: ./helm
        namespace: super-app
        imageStrategy:
          helm: {}
  statusCheckDeadlineSeconds: 600
portForward:
  - resourceType: service
    resourceName: super-app-web
    port: 8000
    localPort: 4000
profiles:
  #
  # Development
  #
  - name: dev
    activation:
      - command: dev
    patches:
      - op: add
        path: /deploy/helm/releases/0/artifactOverrides
        value:
          image: super-app
      - op: add
        path: /deploy/helm/releases/0/overrides
        value:
          mode: 'development'
          redis:
            replica:
              replicaCount: 1
          mongodb:
            useStatefulSet: true
            auth:
              usernames:
                - 'admin'
              passwords:
                - 'password'
              databases:
                - 'db'
  - name: qa
    patches:
      - op: replace
        path: /build/artifacts/0/image
        value: ghcr.io/digital-health-outcomes-models/app-worker
      - op: add
        path: /deploy/helm/releases/0/artifactOverrides
        value:
          image: ghcr.io/digital-health-outcomes-models/app-worker
      - op: add
        path: /deploy/helm/releases/0/overrides
        value:
          mode: 'development'
          image:
            tag: 1.0.0
