kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-config
data: 
  NODE_ENV: {{ .Values.mode }}
  REDIS_HOST: {{ include "redis.host" . | quote }}
  MONGODB_HOST: {{ include "mongodb.host" . | quote }}