mode: prod
storageClass: hostpath
image:
  repository: ghcr.io/digital-health-outcomes-models/app-worker
  tag: latest
  pullPolicy: IfNotPresent
  pullSecretName: githubcred

# Redis
redis:
  sentinel:
    enabled: true
